---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiali-server.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
  {{- if .Values.deployment.secret_annotations }}
  annotations:
    {{- toYaml .Values.deployment.secret_annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  config.yaml: |
    {{- /* Most of .Values is simply the Kiali Config - strip out the keys that are not part of the Config */}}
    {{- $cm := omit .Values "kiali_route_url" }}
    {{- /* The helm chart defines namespace for us, but pass it to the Config in case the server needs it */}}
    {{- $_ := set $cm.deployment "namespace" .Release.Namespace }}
    {{- /* Some values of the ConfigMap are generated, but might not be identical, from .Values */}}
    {{- $_ := set $cm "istio_namespace" (include "kiali-server.istio_namespace" .) }}
    {{- $_ := set $cm.auth "strategy" (include "kiali-server.auth.strategy" .) }}
    {{- $_ := set $cm.auth.openshift "client_id_prefix" (include "kiali-server.fullname" .) }}
    {{- $_ := set $cm.deployment "instance_name" (include "kiali-server.fullname" .) }}
    {{- $_ := set $cm.identity "cert_file" (include "kiali-server.identity.cert_file" .) }}
    {{- $_ := set $cm.identity "private_key_file" (include "kiali-server.identity.private_key_file" .) }}
    {{- $_ := set $cm.login_token "signing_key" (include "kiali-server.login_token.signing_key" .) }}
    {{- $_ := set $cm.external_services.istio "root_namespace" (include "kiali-server.external_services.istio.root_namespace" .) }}
    {{- $_ := set $cm.server "web_root" (include "kiali-server.server.web_root" .) }}
    {{- toYaml $cm | b64enc }}
...
